# Generated by Django 3.1.6 on 2021-03-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bar',
        ),
    ]
