# Generated by Django 3.1.6 on 2021-03-26 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stickers', '0007_auto_20210325_2250'),
        ('accounts', '0002_delete_bar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bartender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bartenders', to=settings.AUTH_USER_MODEL)),
                ('work_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickers.bar')),
            ],
        ),
    ]
