# Generated by Django 3.1.6 on 2021-03-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='total_mlpp',
        ),
        migrations.AddField(
            model_name='shift',
            name='overpouring_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
