# Generated by Django 3.1.6 on 2021-02-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='id',
        ),
        migrations.AddField(
            model_name='sticker',
            name='sticker_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
