# Generated by Django 3.1.6 on 2021-03-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_auto_20210313_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
