# Generated by Django 3.1.6 on 2021-03-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0004_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='mlpp',
        ),
    ]
