# Generated by Django 3.1.6 on 2021-03-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0005_remove_sticker_mlpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='mlpp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
