# Generated by Django 3.1.6 on 2021-04-12 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('stickers', '0007_auto_20210325_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='drink_name',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='drink_size',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='drink_type',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='price',
        ),
        migrations.AddField(
            model_name='sticker',
            name='drink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stickers', to='inventory.drink'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='PouringInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True, null=True)),
                ('volume_poured', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pouring_instances', to='stickers.sticker')),
            ],
        ),
    ]
